"""
Level definitions for StateSmith
Each level is a puzzle with specific DFA requirements
"""

LEVELS = [
    {
        'id': 1,
        'title': 'The First Door',
        'difficulty': 'Tutorial',
        'description': 'Welcome to the dungeon! This door opens for any key ending with "1".',
        'rule': 'Accept strings ending with 1',
        'alphabet': ['0', '1'],
        'good_keys': ['1', '01', '11', '001', '101', '111', '0001'],
        'bad_keys': ['', '0', '10', '00', '110', '1010', '1100'],
        'min_states': 2,
        'max_states': 5,
        'hint': 'You need 2 states: one for "not ending in 1" and one for "ending in 1"',
        'detailed_hint': 'Create 2 states. Make one accept state. From each state, add transitions: 0 stays/goes to non-accept, 1 goes to accept.'
    },
    {
        'id': 2,
        'title': 'The Binary Gate',
        'difficulty': 'Easy',
        'description': 'This ancient door counts in binary. It opens only for even numbers.',
        'rule': 'Accept binary strings representing even numbers (ending with 0 or empty)',
        'alphabet': ['0', '1'],
        'good_keys': ['', '0', '10', '00', '110', '100', '1010', '11110'],
        'bad_keys': ['1', '11', '01', '101', '111', '1011', '10101'],
        'min_states': 2,
        'max_states': 5,
        'hint': 'Even numbers end with 0. Track whether the last digit is 0 or 1.',
        'detailed_hint': '2 states: EVEN (accept) and ODD. From EVEN: 0→EVEN, 1→ODD. From ODD: 0→EVEN, 1→ODD.'
    },
    {
        'id': 3,
        'title': 'The Parity Lock',
        'difficulty': 'Easy',
        'description': 'Count the ones! This door opens when the number of 1s is even.',
        'rule': 'Accept strings with an even number of 1s (including zero 1s)',
        'alphabet': ['0', '1'],
        'good_keys': ['', '0', '00', '11', '0000', '1001', '1100', '110011'],
        'bad_keys': ['1', '10', '01', '001', '111', '10101', '11100'],
        'min_states': 2,
        'max_states': 5,
        'hint': 'Toggle between two states every time you see a 1. Ignore 0s.',
        'detailed_hint': '2 states: EVEN (accept) and ODD. 0 loops to same state. 1 toggles between them.'
    },
    {
        'id': 4,
        'title': 'The Forbidden Pattern',
        'difficulty': 'Medium',
        'description': 'This door rejects any key containing "11" substring. Stay vigilant!',
        'rule': 'Accept strings that do NOT contain "11" as a substring',
        'alphabet': ['0', '1'],
        'good_keys': ['', '0', '1', '01', '10', '001', '010', '101', '0101'],
        'bad_keys': ['11', '011', '110', '111', '0110', '1011', '1110'],
        'min_states': 3,
        'max_states': 6,
        'hint': 'Track: "no 1 seen", "one 1 seen", "two 1s in a row seen (trap)"',
        'detailed_hint': '3 states: START (accept), SAW_ONE_1 (accept), SAW_TWO_1s (reject/trap). Use transitions carefully!'
    },
    {
        'id': 5,
        'title': 'The Sequence Seeker',
        'difficulty': 'Medium',
        'description': 'This magical door opens only for keys containing "101" somewhere.',
        'rule': 'Accept strings containing "101" as a substring',
        'alphabet': ['0', '1'],
        'good_keys': ['101', '0101', '1010', '1101', '1011', '01010', '11011'],
        'bad_keys': ['', '0', '1', '00', '11', '010', '110', '0110', '1100'],
        'min_states': 4,
        'max_states': 7,
        'hint': 'Track progress: none, saw "1", saw "10", saw "101" (accept and stay)',
        'detailed_hint': '4 states tracking: START, SAW_1, SAW_10, SAW_101 (accept, trap). Once in SAW_101, stay there.'
    },
    {
        'id': 6,
        'title': 'The Triple Lock',
        'difficulty': 'Medium',
        'description': 'Three symbols! This door opens for strings starting with A and ending with C.',
        'rule': 'Accept strings that start with "A" and end with "C"',
        'alphabet': ['A', 'B', 'C'],
        'good_keys': ['AC', 'ABC', 'AAC', 'ABBC', 'AABC', 'ABCC', 'AABBCC'],
        'bad_keys': ['', 'A', 'C', 'BC', 'AB', 'BAC', 'BCA', 'CAB', 'ABB'],
        'min_states': 4,
        'max_states': 8,
        'hint': 'Track: "not started", "started with A", "started with A and saw C", "invalid start"',
        'detailed_hint': 'Need states for: START, GOOD_START (saw A), GOOD_END (saw A...C, accept), BAD (didn\'t start with A).'
    },
    {
        'id': 7,
        'title': 'The Divisibility Puzzle',
        'difficulty': 'Hard',
        'description': 'A mathematical riddle! Binary numbers divisible by 3 shall pass.',
        'rule': 'Accept binary strings representing numbers divisible by 3',
        'alphabet': ['0', '1'],
        'good_keys': ['', '0', '11', '110', '1001', '1100', '1111', '10010'],
        'bad_keys': ['1', '10', '100', '101', '111', '1000', '1010', '1011'],
        'min_states': 3,
        'max_states': 6,
        'hint': 'Track remainder when divided by 3. Use modular arithmetic: (n*2 + bit) % 3',
        'detailed_hint': '3 states for remainders: MOD0 (accept), MOD1, MOD2. Transitions based on (2*current + bit) % 3.'
    },
    {
        'id': 8,
        'title': 'The Alternating Path',
        'difficulty': 'Hard',
        'description': 'This mystical door requires perfect alternation: no two consecutive same symbols!',
        'rule': 'Accept strings where no two consecutive characters are the same',
        'alphabet': ['0', '1'],
        'good_keys': ['', '0', '1', '01', '10', '010', '101', '0101', '10101'],
        'bad_keys': ['00', '11', '001', '011', '100', '110', '0011', '1100'],
        'min_states': 3,
        'max_states': 6,
        'hint': 'Track the last symbol seen, plus a "trap" state for violations',
        'detailed_hint': '3 states: SAW_0 (accept), SAW_1 (accept), TRAP (reject). 0 after 0 or 1 after 1 goes to trap.'
    },
    {
        'id': 9,
        'title': 'The Length Checker',
        'difficulty': 'Hard',
        'description': 'Exactly right! This door wants strings of length exactly 4.',
        'rule': 'Accept strings of length exactly 4',
        'alphabet': ['0', '1'],
        'good_keys': ['0000', '0001', '0111', '1111', '1010', '0110', '1100'],
        'bad_keys': ['', '0', '00', '000', '00000', '11111', '010', '10101'],
        'min_states': 5,
        'max_states': 8,
        'hint': 'Count! Make states for length 0, 1, 2, 3, and 4+ (accept at exactly 4)',
        'detailed_hint': '5 states: LEN0, LEN1, LEN2, LEN3, LEN4 (accept), LEN_TOO_LONG (reject). Each symbol advances count.'
    },
    {
        'id': 10,
        'title': 'The Final Challenge',
        'difficulty': 'Expert',
        'description': 'The ultimate test! Strings with odd length AND odd number of 1s.',
        'rule': 'Accept strings that have both odd length AND odd number of 1s',
        'alphabet': ['0', '1'],
        'good_keys': ['1', '001', '010', '100', '00001', '01010', '10100'],
        'bad_keys': ['', '0', '01', '10', '11', '000', '101', '0000', '0011'],
        'min_states': 4,
        'max_states': 8,
        'hint': 'Track TWO things independently: odd/even length AND odd/even count of 1s',
        'detailed_hint': '4 states: EVEN_LEN_EVEN_1s, EVEN_LEN_ODD_1s, ODD_LEN_EVEN_1s, ODD_LEN_ODD_1s (accept). Track both properties!'
    },
    {
        'id': 11,
        'title': 'The Pattern Master',
        'difficulty': 'Expert',
        'description': 'The legendary door! Accept if string contains "01" but NOT "11".',
        'rule': 'Accept strings containing "01" but NOT containing "11"',
        'alphabet': ['0', '1'],
        'good_keys': ['01', '001', '010', '0010', '00101', '010101'],
        'bad_keys': ['', '0', '1', '10', '11', '011', '110', '0011', '1011'],
        'min_states': 5,
        'max_states': 10,
        'hint': 'Combine two patterns: track progress toward "01" while avoiding "11"',
        'detailed_hint': 'States: START, SAW_0 (can lead to 01), SAW_01 (accept), SAW_1 (dangerous!), TRAP (saw 11). Very tricky!'
    },
    {
        'id': 12,
        'title': 'The Grand Finale',
        'difficulty': 'Master',
        'description': 'The ultimate door! Binary multiples of 5. Only the wisest escape...',
        'rule': 'Accept binary strings representing numbers divisible by 5',
        'alphabet': ['0', '1'],
        'good_keys': ['', '0', '101', '1010', '1111', '10100', '11001', '11110'],
        'bad_keys': ['1', '10', '11', '100', '110', '111', '1000', '1011'],
        'min_states': 5,
        'max_states': 10,
        'hint': 'Track remainder mod 5: states for remainders 0,1,2,3,4. Accept at remainder 0.',
        'detailed_hint': '5 states for MOD0-4. Transition: new_remainder = (old_remainder * 2 + bit) % 5. MOD0 is accept state.'
    }
]
